# Generated by Django 3.2.9 on 2021-12-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='zamieszczane/zdjecia_profilowe/profi_img.png', upload_to='zamieszczane/zdjecia_profilowe'),
        ),
    ]
