# Generated by Django 3.2.9 on 2021-12-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/zamieszczane/zdj_posty'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='media/zamieszczane/zdjecia_profilowe/profi_img.png', upload_to='media/zamieszczane/zdjecia_profilowe'),
        ),
    ]
