# Generated by Django 3.2.9 on 2021-12-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_auto_20211217_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='zamieszczane/zdj_posty'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='zamieszczane/zdjecia_profilowe/profi_img.png', upload_to='zamieszczane/zdjecia_profilowe'),
        ),
    ]
